=== social-computing/jmi-server/jmi-server/src/main/webapp/dtd/WPS-dictionary.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ENTITY % JDBC-entities SYSTEM "JDBC-connector.dtd" >
%JDBC-entities;

<!ENTITY % REST-entities SYSTEM "REST-connector.dtd" >
%REST-entities;

<!ENTITY % SOLR-entities SYSTEM "SOLR-connector.dtd" >
%SOLR-entities;

<!ENTITY % Google-entities SYSTEM "Google-connector.dtd" >
%Google-entities;

<!ENTITY % Relax-params SYSTEM "Relax-params.dtd" >
%Relax-params;

<!-- =====================================================================  -->
<!-- shared -->
<!-- =====================================================================  -->
<!-- a comment -->
<!ELEMENT comment 			(#PCDATA)>

<!-- an URL connection -->
<!ELEMENT URL-connection 	(url,basic-authentication?,url-header*,url-parameter*)>
<!ATTLIST URL-connection 	type	CDATA    "GET">

<!ELEMENT url 				(#PCDATA)>

<!ELEMENT url-header 	(#PCDATA)>
<!ATTLIST url-header name 		NMTOKEN 	#REQUIRED>
<!ATTLIST url-header default 	CDATA 		#IMPLIED>

<!ELEMENT url-parameter 	(#PCDATA)>
<!ATTLIST url-parameter name 	NMTOKEN 	#REQUIRED>
<!ATTLIST url-parameter default CDATA 		#IMPLIED>

<!-- Basic authentication -->
<!ELEMENT basic-authentication EMPTY>
<!ATTLIST basic-authentication username CDATA 	#REQUIRED>
<!ATTLIST basic-authentication password CDATA 	#REQUIRED>


<!-- =====================================================================  -->
<!-- Dictionaries -->
<!-- =====================================================================  -->
<!ELEMENT dictionaries (dictionary+)>

<!-- =====================================================================  -->
<!-- Dictionary -->
<!-- =====================================================================  -->
<!ELEMENT dictionary (comment?, entities, env-property*, filtering-scheduling?, filtering-profile*, affinity-reader-profile+, analysis-profile+, display-profile+, segmentation)>
<!ATTLIST dictionary name   NMTOKEN 	#REQUIRED>

<!ELEMENT entities (JDBC-entities|REST-entities|SOLR-entities|Google-entities)>

<!-- =====================================================================  -->
<!-- Env Properties : fixing env properties -->
<!-- =====================================================================  -->
<!ELEMENT env-property EMPTY>
<!ATTLIST env-property name  	CDATA    #REQUIRED>
<!ATTLIST env-property value 	CDATA    #REQUIRED>

<!-- =====================================================================  -->
<!-- Filtering scheduling  -->
<!-- =====================================================================  -->
<!ELEMENT filtering-scheduling (filtering-scheduling-timer|filtering-scheduling-time) >

<!ELEMENT filtering-scheduling-timer EMPTY>
<!ATTLIST filtering-scheduling-timer timer 	CDATA    "60">

<!ELEMENT filtering-scheduling-time  EMPTY>
<!ATTLIST filtering-scheduling-time time 	CDATA    "00:00">

<!-- =====================================================================  -->
<!-- Filtering Profile : fixing parameters and connector -->
<!-- =====================================================================  -->
<!ELEMENT filtering-profile (comment?)>
<!ATTLIST filtering-profile name     		CDATA    #REQUIRED>
<!ATTLIST filtering-profile attributes-ref	CDATA    #REQUIRED>
<!ATTLIST filtering-profile threshold 		CDATA    "60">
<!ATTLIST filtering-profile max-attribute 	CDATA    "1000">
<!ATTLIST filtering-profile tmp-dir			CDATA    #IMPLIED>

<!-- =====================================================================  -->
<!-- Affinity Reader Profile : fixing parameters and connector -->
<!-- =====================================================================  -->
<!ELEMENT affinity-reader-profile (comment?)>
<!ATTLIST affinity-reader-profile name     				CDATA    #REQUIRED>
<!ATTLIST affinity-reader-profile affinity-reader-ref	CDATA    #IMPLIED>
<!ATTLIST affinity-reader-profile threshold 			CDATA    "60">
<!ATTLIST affinity-reader-profile max-entities 			CDATA    "2000">

<!-- =====================================================================  -->
<!-- Analysis Profile : fixing parameters and connector -->
<!-- =====================================================================  -->
<!ELEMENT analysis-profile (comment?, props-mapping?, entities-recommendation?, attributes-recommendation?, subattributes-recommendation?, relax?)>
<!ATTLIST analysis-profile name     					CDATA    #REQUIRED>
<!ATTLIST analysis-profile attributes-ref				CDATA    #REQUIRED>
<!ATTLIST analysis-profile type							(personal|global|discovery) "personal">
<!ATTLIST analysis-profile attribute-size				(frequency|ponderation|max-ponderation|same) "frequency">
<!ATTLIST analysis-profile cluster						(yes|no) "yes">
<!ATTLIST analysis-profile self-clustering-property		CDATA	 #IMPLIED>
<!ATTLIST analysis-profile force-clustering-property	CDATA	 #IMPLIED>
<!ATTLIST analysis-profile cluster-level				CDATA    "50"> <!-- % between 0 and 100 -->
<!ATTLIST analysis-profile cluster-threshold			CDATA    "20">	<!-- % between 0 and 100 -->
<!ATTLIST analysis-profile cluster-type					(size|ponderation) "size">
<!ATTLIST analysis-profile attributes-cluster-max		CDATA    "7">
<!ATTLIST analysis-profile balanced-effect				CDATA    "0">
<!ATTLIST analysis-profile entities-max					CDATA    "100">
<!ATTLIST analysis-profile attributes-max				CDATA    "60">
<!ATTLIST analysis-profile attributes-base-max			CDATA    "30">
<!ATTLIST analysis-profile attr-link-threshold			CDATA    "10"> <!-- % between 0 and 100 -->
<!ATTLIST analysis-profile links-attribute-threshold	CDATA    "3"> <!-- >=1 -->

<!ELEMENT entities-recommendation (mapping*)>
<!ATTLIST entities-recommendation apply			(all|base|notbase) "all">
<!ATTLIST entities-recommendation max			CDATA    "10">
<!ATTLIST entities-recommendation threshold		CDATA    "20">  <!-- % between 0 and 100 -->

<!ELEMENT attributes-recommendation (mapping*)>
<!ATTLIST attributes-recommendation apply			(all|base|notbase) "all">
<!ATTLIST attributes-recommendation max				CDATA    "10">
<!ATTLIST attributes-recommendation threshold		CDATA    "20">  <!-- % between 0 and 100 -->

<!ELEMENT subattributes-recommendation (mapping*)>
<!ATTLIST subattributes-recommendation apply		(all|base|notbase) "all">
<!ATTLIST subattributes-recommendation max			CDATA    "10">
<!ATTLIST subattributes-recommendation threshold	CDATA    "20">  <!-- % between 0 and 100 -->

<!-- Swatchs => DB Properties Names Mapping -->
<!ELEMENT props-mapping (entity-props-mapping?, attribute-props-mapping?, subattribute-props-mapping?)>
<!ELEMENT entity-props-mapping (comment?, mapping*)>
<!ATTLIST entity-props-mapping all-properties	(true|false) "false">
<!ELEMENT attribute-props-mapping (comment?, mapping*)>
<!ATTLIST attribute-props-mapping all-properties	(true|false) "false">
<!ELEMENT subattribute-props-mapping (comment?, mapping*)>
<!ATTLIST subattribute-props-mapping all-properties	(true|false) "false">

<!-- Mapping -->
<!ELEMENT mapping EMPTY>
<!ATTLIST mapping key   CDATA    #REQUIRED>
<!ATTLIST mapping value CDATA    #REQUIRED>

<!-- Relax -->
<!ELEMENT relax ( stage* )>
	<!ATTLIST relax	linkBaseLen 	CDATA   "8 10"
					linkMixedLen	CDATA   "8 10"
					linkExtLen	 	CDATA   "8 10"
					nodeSize		CDATA   "2.5 3.5"
					linkWidth       CDATA   ".5 1.5"
					linkBaseStiff 	CDATA   ".5 1"
					linkMixedStiff	CDATA   ".5 1"
					linkExtStiff 	CDATA   ".5 1"
					margin			CDATA	"5"
					baseLinkMin		CDATA	"1"
					baseLinkMax		CDATA	"5"
					baseLinkKeep	CDATA	".25"
					mixedLinkMin	CDATA	"1"
					mixedLinkMax	CDATA	"3"
					mixedLinkKeep	CDATA	".25"
					extLinkMin		CDATA	"1"
					extLinkMax		CDATA	"4"
					extLinkKeep		CDATA	".25">

<!-- Stage -->
<!ELEMENT stage EMPTY>
	<!ATTLIST stage	name			(baseRelax|baseFilter|extRelax|extFilter|extLast)	#REQUIRED
					scale 			CDATA   ".2"
					nodeRep    		CDATA   ".2"
					nodeRepMix		CDATA   ".75"
					linkTens		CDATA   ".2"
					linkTensMix		CDATA   ".5"
					linkRep			CDATA   ".5"
					linkRepMix		CDATA   ".75"
					linkRot			CDATA   "0"
					crossRep		CDATA   "0"
					iterCnt			CDATA   "50"
					errorTrsh		CDATA   ".002"
					lastIterCnt		CDATA   #IMPLIED
					lastErrorTrsh	CDATA   #IMPLIED>

<!-- =====================================================================  -->
<!-- Display Profile : fixing plan parameters and swatchs -->
<!-- =====================================================================  -->
<!ELEMENT display-profile (comment?, swatch-segmentation, selection-swatch*)>
<!ATTLIST display-profile name     				CDATA    #REQUIRED>
<!ATTLIST display-profile display-entities   	(yes|no)   "no">
<!ATTLIST display-profile display-empty-links   (yes|no)   "yes">
<!ATTLIST display-profile display-fake-links   	(yes|no)   "yes">
<!ATTLIST display-profile in-color				CDATA    #IMPLIED>
<!ATTLIST display-profile out-color				CDATA    #IMPLIED>
<!ATTLIST display-profile filter-color			CDATA    #IMPLIED>

<!-- Swatch Segmentation -->
<!ELEMENT swatch-segmentation (attribute-swatch, link-swatch)>

<!ELEMENT attribute-swatch (norm-swatch, ref-swatch, active-norm-swatch, active-ref-swatch)>
<!ELEMENT link-swatch (norm-swatch, ref-swatch, ( active-norm-swatch, active-ref-swatch )?)>

<!ELEMENT norm-swatch (classifier-ref?)>
<!ATTLIST norm-swatch default-ref   CDATA    #REQUIRED>
<!ELEMENT ref-swatch (classifier-ref?)>
<!ATTLIST ref-swatch default-ref   CDATA    #REQUIRED>
<!ELEMENT active-norm-swatch (classifier-ref?)>
<!ATTLIST active-norm-swatch default-ref   CDATA    #REQUIRED>
<!ELEMENT active-ref-swatch (classifier-ref?)>
<!ATTLIST active-ref-swatch default-ref   CDATA    #REQUIRED>

<!ELEMENT selection-swatch EMPTY>
<!ATTLIST selection-swatch name  		  CDATA    #REQUIRED>
<!ATTLIST selection-swatch selection-ref  CDATA    #IMPLIED>

<!-- Classifier Ref -->
<!ELEMENT classifier-ref (mapping*)>
<!ATTLIST classifier-ref classifier   CDATA    #REQUIRED>

<!-- =====================================================================  -->
<!-- Segmentation : requesting entity fixes profiles -->
<!-- =====================================================================  -->
<!ELEMENT segmentation (filtering-segmentation?, analysis-segmentation, affinity-reader-segmentation, display-segmentation)>

<!-- Fixes Filtering Profile -->
<!ELEMENT filtering-segmentation (classifier-ref?)>
<!ATTLIST filtering-segmentation default-ref   CDATA    #REQUIRED>

<!-- Fixes Analysis Profile -->
<!ELEMENT analysis-segmentation (classifier-ref?)>
<!ATTLIST analysis-segmentation default-ref   CDATA    #REQUIRED>

<!-- Fixes Affinity Reader according Analysis Profile -->
<!ELEMENT affinity-reader-segmentation (classifier-ref?, affreader-analysis-mapping*)>
<!ATTLIST affinity-reader-segmentation default-ref   CDATA    #REQUIRED>

<!ELEMENT affreader-analysis-mapping (classifier-ref?)>
<!ATTLIST affreader-analysis-mapping analysis-ref CDATA    #REQUIRED>
<!ATTLIST affreader-analysis-mapping default-ref   CDATA    #REQUIRED>

<!-- Fixes display-profile according Analysis Profile and Language -->
<!ELEMENT display-segmentation (classifier-ref?, display-language-mapping*, display-analysis-mapping*)>
<!ATTLIST display-segmentation default-ref   CDATA    #REQUIRED>

<!ELEMENT display-analysis-mapping (display-language-mapping*)>
<!ATTLIST display-analysis-mapping analysis-ref CDATA    #REQUIRED>
<!ATTLIST display-analysis-mapping default-ref  CDATA    #REQUIRED>

<!ELEMENT display-language-mapping (classifier-ref?)>
<!ATTLIST display-language-mapping language   	CDATA    #REQUIRED>
<!ATTLIST display-language-mapping default-ref  CDATA    #REQUIRED>

=== social-computing/jmi-server/web-feeds/ressources/definitions/feeds-dictionary.xml
<?xml version='1.0' encoding='ISO-8859-1'?>

<!DOCTYPE dictionary SYSTEM "WPS-dictionary.dtd" >

<dictionary name="Feeds" >
	<comment>Feeds Categories Dictionary</comment>

	<entities>
		<Feeds-entities name="Media Sociaux">
			<URL-connection>
				<url>{$feed}</url>
			</URL-connection>
		</Feeds-entities>
	</entities>
	
	<env-property name="$web_context" value ="http://localhost:8080/wps-server/" />
	
	<affinity-reader-profile name="AffReader" affinity-reader-ref="*" threshold="100" />
	<affinity-reader-profile name="DiscoveryAffReader" affinity-reader-ref="*" threshold="100" />
	<affinity-reader-profile name="GlobalAffReader" affinity-reader-ref="*" threshold="100" />

	<analysis-profile name="Profile" attributes-ref="JDBC_Profile" type="personal" attribute-size="frequency">
		<props-mapping>
			<entity-props-mapping>
				<mapping key="ID" 	value="id" />
				<mapping key="NAME" value="name" />
			</entity-props-mapping>
			<attribute-props-mapping>
				<mapping key="ID" 	value="id" />
				<mapping key="NAME" value="name" />
				<mapping key="POSS_ID" 	value="poss_id" />
				<mapping key="POSS_NAME" value="poss_name" />
			</attribute-props-mapping>
		</props-mapping>
		<entities-recommendation>
			<mapping key="REC_ID"  		value="id" />
			<mapping key="REC_NAME"  	value="name" />
		</entities-recommendation>
	</analysis-profile>

	<analysis-profile name="DiscoveryProfile" attributes-ref="JDBC_Profile" type="discovery" attribute-size="frequency" attributes-max="300" >
		<props-mapping>
			<entity-props-mapping>
				<mapping key="ID" 	value="id" />
				<mapping key="NAME" value="name" />
			</entity-props-mapping>
			<attribute-props-mapping>
				<mapping key="ID" 	value="id" />
				<mapping key="NAME" value="name" />
				<mapping key="POSS_ID" 	value="poss_id" />
				<mapping key="POSS_NAME" value="poss_name" />
			</attribute-props-mapping>
		</props-mapping>
		<entities-recommendation>
			<mapping key="REC_ID"  		value="id" />
			<mapping key="REC_NAME"  	value="name" />
		</entities-recommendation>
	</analysis-profile>

	<analysis-profile name="GlobalProfile" attributes-ref="JDBC_Profile" type="global" attribute-size="same" attributes-max="60" >
		<props-mapping>
			<entity-props-mapping>
				<mapping key="ID" 	value="id" />
				<mapping key="NAME" value="name" />
			</entity-props-mapping>
			<attribute-props-mapping>
				<mapping key="ID" 	value="id" />
				<mapping key="NAME" value="name" />
				<mapping key="POSS_ID" 	value="poss_id" />
				<mapping key="POSS_NAME" value="poss_name" />
			</attribute-props-mapping>
		</props-mapping>
		<entities-recommendation>
			<mapping key="REC_ID"  		value="id" />
			<mapping key="REC_NAME"  	value="name" />
		</entities-recommendation>
	</analysis-profile>

	<display-profile name="Display" display-empty-links="no" in-color="FFFFFF" out-color="0" filter-color="FFFFFF" >
		<swatch-segmentation>
			<attribute-swatch>
				<norm-swatch default-ref="FEED_NODE_NORM" />
				<ref-swatch default-ref="FEED_NODE_REF" />
				<active-norm-swatch default-ref="FEED_NODE_CUR_NORM" />
				<active-ref-swatch default-ref="FEED_NODE_CUR_REF" />
			</attribute-swatch>
			<link-swatch>
				<norm-swatch default-ref="FEED_LINK_NORM" />
				<ref-swatch default-ref="FEED_LINK_REF" />
				<active-norm-swatch default-ref="FEED_LINK_CUR_NORM" />
				<active-ref-swatch default-ref="FEED_LINK_CUR_REF" />
			</link-swatch>
		</swatch-segmentation>
		<selection-swatch name="search" />
	</display-profile>

	<display-profile name="GlobalDisplay" display-empty-links="no" display-fake-links="no" in-color="FFFFFF" out-color="0" filter-color="FFFFFF" >
		<swatch-segmentation>
			<attribute-swatch>
				<norm-swatch default-ref="FEED_NODE_NORM" />
				<ref-swatch default-ref="FEED_NODE_REF" />
				<active-norm-swatch default-ref="FEED_NODE_CUR_NORM" />
				<active-ref-swatch default-ref="FEED_NODE_CUR_REF" />
			</attribute-swatch>
			<link-swatch>
				<norm-swatch default-ref="FEED_LINK_NORM" />
				<ref-swatch default-ref="FEED_LINK_REF" />
				<active-norm-swatch default-ref="FEED_LINK_CUR_NORM" />
				<active-ref-swatch default-ref="FEED_LINK_CUR_REF" />
			</link-swatch>
		</swatch-segmentation>
		<selection-swatch name="search" />
	</display-profile>

	<segmentation>
		<analysis-segmentation  default-ref="Profile" />
		<affinity-reader-segmentation default-ref="AffReader" >
			<affreader-analysis-mapping analysis-ref="DiscoveryProfile" default-ref="DiscoveryAffReader" />
			<affreader-analysis-mapping analysis-ref="GlobalProfile" default-ref="GlobalAffReader" />
		</affinity-reader-segmentation>
		<display-segmentation default-ref="Display" >
			<display-analysis-mapping analysis-ref="GlobalProfile" default-ref="GlobalDisplay" />
		</display-segmentation>
	</segmentation>
	
</dictionary>
